version: '3.7'

services:
  database_mysql:
    image: mysql
    container_name: database_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: DbTsundoku
      MYSQL_USER: tsun
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql